version: '2.1'
orbs:
  terraform: circleci/terraform@dev:alpha
jobs:
  plan-apply:
    working_directory: /tmp/project
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            terraform init -input=false
            terraform plan -out tfapply -var-file variables.tfvars
      - persist_to_workspace:
          root: .
          paths:
            - .
workflows:
  plan-apply:
    jobs:
      - plan-apply
